### ISSUE TITLE
Potential bug in calculation of luminosity for unbinned stars

### ISSUE THREAD

**Issue by anchwr** [dnarayanan/powderday#103]
I think there's a bug in the calculation of luminosity for unbinned star particles in source_creation.py. In the function direct_add_stars, the luminosity of each individual unbinned star particle is calculated by integrating over the spectrum of the star particle and multiplying by its mass. However, the mass list that's being iterated over (stars_list.mass) contains the masses of every star particle in the simulation, while the list of spectra includes only unbinned star particles, so that the spectrum of one star particle is matched up with the mass of another. This isn't an issue if all star particles are the same mass, but produces incorrect luminosities for simulations with a wide variety of stellar masses. Should the mass list being iterated over be unbinned_stars_list.mass instead? I've linked the relevant line below.

https://github.com/dnarayanan/powderday/blob/f02653f629c0645ba836843857b41a4bba28b4bd/powderday/source_creation.py#L56

**Comment by dnarayanan** [comment]
Thanks for reporting this!  I'm looping in @prerakgarg07 who wrote this code -- he thinks that you're right and we very much appreciate the ticket.   he's running some tests now and hopefully we'll have a pull request/fix later today.

**Comment by dnarayanan** [comment]
fixed by PR https://github.com/dnarayanan/powderday/pull/104
