### ISSUE TITLE
Nebular Emission for Low-Mass Star Particles

### ISSUE THREAD

**Issue by anchwr** [dnarayanan/powderday#111]
I am currently working with a set of simulations that have star particles that form with masses as low as 1000 Msol. As this is lower than the smallest cluster mass used in calculating nebular emission, I can't run powderday with nebular emission turned on for these simulations. Is there a way to calculate nebular emission without modeling star particles as multiple clusters/are there plans to implement nebular emission calculations for high resolution simulations like these in the future? If not (or even in the meantime), it might be helpful to add some kind of if statement to check that the minimum mass of star particles for which nebular emission would be calculated is above 10^3.5 Msol, and, if not, to print a warning and turn nebular emission off, so that the user doesn't end up with a spectrum full of NaNs. I'd be happy to add this and do a pull request if that would be useful.

**Comment by dnarayanan** [comment]
thanks for the query/bug report!  @prerakgarg07 issued a new commit to take care of this here:

https://github.com/dnarayanan/powderday/pull/112

which is now merged into main.   let me know if this works for you please!

**Comment by anchwr** [comment]
Oh, awesome! Thank you so much! I'll update as soon as my current pd run finishes and let you know.

**Comment by anchwr** [comment]
Finally made it through the queue. This works! Thank you so much!
