### ISSUE TITLE
astropy.extern.six no longer exists

### ISSUE THREAD

**Issue by dnarayanan** [dnarayanan/powderday#34]
if you install `astropy` separately as the 4.x intallation docs for `pd` suggest you should do, then you'll end up in a situation where `hyperion.model.model` requires astropy.extern.six which doesn't exist in versions after astropy4.0.   

so, we should update docs for how to deal wiht this.  basically:
[1] need to download and pip install hyperion
[2] then reinstall yt4.x after that so it uninstalls the yt3.x that shipped with hyperion

**Comment by dnarayanan** [comment]
alternatively can manually edit all thse codes in `hyperion`

https://github.com/hyperion-rt/hyperion/issues/219

**Comment by RaySSharma** [comment]
A hacky alternative is to manually place _six.py_ within `astropy.extern`, though that may break with updates to `astropy`.

**Comment by jwise77** [comment]
I just submitted a hyperion PR, so hopefully it's accepted and this issue can be resolved!

**Comment by dnarayanan** [comment]
closed as this was merged in hyperion thanks to john's PR!
