### ISSUE TITLE
Improper exception handling in Nenkova agn_model

### ISSUE THREAD

**Issue by RaySSharma** [dnarayanan/powderday#7]
If BH_model = "Nenkova" is set, Powderday tries to load in the Nenkova BH model file. If it fails at finding the file, it raises a FileNotFoundError, which does not exist in Python 2.7. The better error to raise would be IOError, which exists in both Python 2/3.

**Comment by dnarayanan** [comment]
resolved by 8e838e2651f9bede3613c1afa6b6f345145fdc05
